# Generated by Django 4.2.1 on 2023-11-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.TextField(default='')),
                ('contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('total', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
